package effects;

public enum DropShadowParametersEnum {
	DROP_SHADOW_RADIUS,
	DROP_SHADOW_WIDTH,
	DROP_SHADOW_HEIGHT,
	DROP_SHADOW_BLUR_TYPE,
	DROP_SHADOW_SPREAD,
	DROP_SHADOW_COLOR,
	DROP_SHADOW_OFFSETX,
	DROP_SHADOW_OFFSETY	
}
